/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarInput: typeof import('./src/components/AvatarInput.vue')['default']
    ButtonSignIn: typeof import('./src/components/ButtonSignIn.vue')['default']
    ClickNow: typeof import('./src/components/icons/ClickNow.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAddToCart: typeof import('./src/components/icons/IconAddToCart.vue')['default']
    IconAddToCart2: typeof import('./src/components/icons/IconAddToCart2.vue')['default']
    IconArrowRight: typeof import('./src/components/icons/IconArrowRight.vue')['default']
    IconBra: typeof import('./src/components/icons/IconBra.vue')['default']
    IconCart: typeof import('./src/components/icons/IconCart.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDeleteCart: typeof import('./src/components/icons/IconDeleteCart.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconGirl: typeof import('./src/components/icons/IconGirl.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconLike: typeof import('./src/components/icons/IconLike.vue')['default']
    IconOption: typeof import('./src/components/icons/IconOption.vue')['default']
    IconOutOfStock: typeof import('./src/components/icons/IconOutOfStock.vue')['default']
    IconPrice: typeof import('./src/components/icons/IconPrice.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSell: typeof import('./src/components/icons/IconSell.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTick: typeof import('./src/components/icons/IconTick.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    IconVote: typeof import('./src/components/icons/IconVote.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    OptionSearch: typeof import('./src/components/OptionSearch.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    PromoDetail: typeof import('./src/components/PromoDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UsernameInput: typeof import('./src/components/UsernameInput.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
